### ISSUE TITLE
hello, I am trying your firmare BUT how can I get arm-none-eabi-gcc (15:4.9.3+svn231177-1) ?

### ISSUE THREAD

**Issue by Merafour** [pysco68/waveshare-hid#5]
hello, I am trying your firmare BUT how can I get arm-none-eabi-gcc (15:4.9.3+svn231177-1) ?

**Comment by pysco68** [comment]
Hello, the exact version doesn't really matter.

If you're on a recent version of Ubuntu you can just `sudo apt-get install gcc-arm-none-eabi` (at least on 16.10 that worked)

Furthermore you'll probably want to have the build essentials installed too: `sudo apt-get install build-essential`

**Comment by Merafour** [comment]
Thank you!
